name = "Paper Plus"
license = "MIT"
licenselink = "https://github.com/mmshivesh/hugo-paper-plus/blob/master/LICENSE"
description = "Paper Plus, a fork of Paper theme that builds on the original Paper with lots of new features."
homepage = "https://github.com/mmshivesh/hugo-paper-plus/"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"
